# 特殊语句

## assert语句

assert 语句是在程序中插入调试性断言的简便方式

assert 语句在Python中主要用于调试目的，以确保代码在运行时满足某些条件。

如果条件不满足（即条件表达式的结果为False），则assert会抛出一个AssertionError异常，并可以选择性地显示一个错误消息。

这种机制对于快速发现和定位代码中的错误非常有用。

```
assert_stmt ::=  "assert" expression ["," expression]

assert 条件表达式, "错误消息"
```

* 条件表达式：这是一个布尔表达式，assert会检查它的值。如果值为True，则assert语句什么也不做，程序继续执行。如果值为False，则抛出AssertionError。
* 错误消息（可选）：这是一个字符串，当条件表达式为False时，它会被用作AssertionError异常的错误消息。如果未提供，则使用默认的错误消息。


```python
assert 2 + 2 == 4
```

不会抛错，继续执行程序

```python
assert 2 + 2 == 5
```

会抛出AssertionError异常

```python
assert 2 + 2 == 5, "2 + 2 不等于 5"
```

会抛出AssertionError异常，错误消息为"2 + 2 不等于 5"


## yield语句

yield 表达式在定义 generator 函数或 asynchronous generator 函数时才会用到因此只能在函数定义的内部使用。

在一个函数体内使用 yield 表达式会使这个函数变成一个生成器函数，而在一个 async def 函数的内部使用它则会让这个协程函数变成一个异步生成器函数。

```python
def gen():  # 定义一个生成器函数
    yield 123

async def agen(): # 定义一个异步生成器函数
    yield 123
```

yield 语句在Python中是一个非常重要的特性，它主要用于从一个函数中返回一系列的值，而不是一次性返回一个值。

这种函数被称为生成器（generator）。

生成器提供了一种便捷的方式来实现迭代器协议，而不需要定义`__iter__()`和`__next__()`方法。

当你调用一个包含yield语句的函数时，该函数不会立即执行其体中的所有语句，而是返回一个迭代器对象。

每次使用next()函数（或在循环中迭代）调用这个迭代器时，函数将执行到下一个yield语句，并返回该语句的值。

然后，函数执行将暂停，直到下一次迭代。

yeild语句的特性:
* 暂停和恢复：yield允许函数在执行过程中暂停，并在下一次迭代时从上次暂停的地方继续执行。
* 节省内存：生成器非常适合处理大量数据，因为它们一次只处理数据的一部分，而不是一次性将所有数据加载到内存中。
* 简洁性：与手动实现迭代器相比，使用yield可以使代码更加简洁和易于理解。

```python
def my_generator():  
    yield 1  
    yield 2  
    yield 3  

gen = my_generator()

print(next(gen)) # 1
print(next(gen)) # 2
print(next(gen)) # 3
```

```python
def my_generator():  
    yield 1  
    yield 2  
    yield 3  

gen = my_generator()

for value in gen:  
    print(value)
```

```python
def my_generator():  
    yield 1  
    yield 2  
    yield 3  

gen = my_generator()

while True:  
    try:  
        print(next(gen))  
    except StopIteration:  
        break
```

生成器的控制权是由调用者决定的，而不是由生成器内部的控制流决定的。

```python
def my_generator():  
    for i in range(10):  
        yield i  
        print("yielded")  
        time.sleep(1)  # 暂停一秒  
  
g = my_generator()  
  
while True:  
    try:  
        value = next(g)  
        print(value)  
    except StopIteration:  
        break
```

在Python的生成器中，for 循环（或任何包含 yield 语句的代码块）实际上并不会像普通的 for 循环那样一直执行到完成。相反，当生成器函数中的代码遇到 yield 语句时，它会暂停执行，并将控制权交还给生成器的调用者（即 next(g) 的调用者）。此时，生成器函数中的 for 循环（或任何其他控制流结构）实际上是被“挂起”的，处于暂停状态。

在调用者使用 next(g) 请求下一个值时，生成器会从上次暂停的地方（即 yield 语句之后）继续执行，直到遇到下一个 yield 语句或函数结束（此时会抛出 StopIteration 异常）。然后，这个过程会重复进行，直到生成器中的所有值都被生成完毕。

案例1：
```python
>>> def g(x):
>>>     yield from range(x, 0, -1)
>>>     yield from range(x)

>>> list(g(5))
[5, 4, 3, 2, 1, 0, 1, 2, 3, 4]
```

案例2：
```python
>>> def echo(value=None):
>>>     print("Execution starts when 'next()' is called for the first time.")
>>>     try:
>>>         while True:
>>>             try:
>>>                 value = (yield value)
>>>             except Exception as e:
>>>                 value = e
>>>     finally:
>>>         print("Don't forget to clean up when 'close()' is called.")

>>> generator = echo(1)
>>> print(next(generator))
Execution starts when 'next()' is called for the first time.
1
>>> print(next(generator))
None
>>> print(generator.send(2))
2
>>> generator.throw(TypeError, "spam")
TypeError('spam',)
>>> generator.close()
Don't forget to clean up when 'close()' is called.
```